force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Distinguishes between area / region and residential / commercial property.</description>
    <inlineHelpText>Distinguishes between area / region and residential / commercial property.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Region</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Market Area</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LocationHelper.cls
public class LocationHelper {
    public static Map<String, Location__c> areasMap;
    // Builds areasMap to be able to search based on Name
    public static void setAreasMap() {
        if(areasMap == null) {
            areasMap = new Map<String, Location__c>();
            // Selects Market Areas records
            for(Location__c location : [SELECT Id, Name FROM Location__c WHERE Type__c =: Constants.LOCATION_TYPE_2]) {
                areasMap.put(location.Name, location);
}   }   }   }