force-app/main/default/objects/Campaign/fields/UTM__c.field-meta.xml
<CustomField>
    <fullName>UTM__c</fullName>
    <label>UTM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Registered_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Registered_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Property</value>
        </filterItems>
        <infoMessage>Only locations of type property are allowed.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Registered_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Market_Area__c.field-meta.xml
<CustomField>
    <fullName>Market_Area__c</fullName>
    <label>Market Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/UPRN__c.field-meta.xml
<CustomField>
    <fullName>UPRN__c</fullName>
    <label>UPRN</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/UTM__c.field-meta.xml
<CustomField>
    <fullName>UTM__c</fullName>
    <label>UTM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/UTM__c.field-meta.xml
<CustomField>
    <fullName>UTM__c</fullName>
    <label>UTM</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Parent_Location__c.field-meta.xml
<CustomField>
    <fullName>Parent_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This allows us to relate a location to the correct location. Additionally, it allows us to be able to quckly do roll up summaries of the child records.</description>
    <inlineHelpText>Lookup field on the location record to the different area type. e.g. market area or region.</inlineHelpText>
    <label>Parent Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Related Locations</relationshipLabel>
    <relationshipName>Related_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/UPRN__c.field-meta.xml
<CustomField>
    <fullName>UPRN__c</fullName>
    <label>UPRN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/recordTypes/Area.recordType-meta.xml
<RecordType>
    <fullName>Area</fullName>
    <active>true</active>
    <label>Area</label>
</RecordType>

force-app/main/default/classes/InteractionTriggerHandler.cls
public class InteractionTriggerHandler {
    public static void linkRecords(List<Interaction__c> interactions) {
        Map<String, Interaction__c> interactionsByEmail = new Map<String, Interaction__c>();
        Map<String, Interaction__c> interactionsByUPRN  = new Map<String, Interaction__c>();
        Map<String, Interaction__c> interactionsByUTM   = new Map<String, Interaction__c>();
        /*
        for(Interaction__c interaction : interactions) {
            // Builds interactionsByUPRN to be able to search Interactions based on UPRN
            if(String.isNotBlank(interaction.UPRN__c)) {
                interactionsByUPRN.put(interaction.UPRN__c, interaction);
                // Builds interactionsByEmail to be able to search Interactions based on Email
                if(String.isNotBlank(interaction.Email__c)) {
                    interactionsByEmail.put(interaction.Email__c, interaction);
                }
                // Builds interactionsByUTM to be able to search Interactions based on UTM
                if(String.isNotBlank(interaction.UTM__c)) {
                    interactionsByUTM.put(interaction.UTM__c, interaction);
        }   }   }
        // TBD - Locations might not always have a UPRN and in that case we can use Address Key
        if(interactionsByUPRN.size() > 0) {
            Map<String, Campaign> campaignsByUTM      = new Map<String, Campaign>();
            Map<String, Lead> leadsByEmail            = new Map<String, Lead>();
            Map<String, Location__c> locationsByEmail = new Map<String, Location__c>();
            Map<String, Location__c> locationsByUPRN  = new Map<String, Location__c>();
            List<Lead> newLeads                       = new List<Lead>();
            List<Location__c> newLocations            = new List<Location__c>();
            // Builds a map with Market Areas by Name
            LocationHelper.setAreasMap();
            // Builds locationsByUPRN to be able to search existing Locations based on UPRN
            for(Location__c location : [SELECT Id, Account__c, UPRN__c FROM Location__c WHERE UPRN__c IN : interactionsByUPRN.keySet()]) {
                locationsByUPRN.put(location.UPRN__c, location);
            }
            if(interactionsByEmail.size() > 0) {
                // Builds leadsByEmail to be able to search existing Leads based on Email
                for(Lead lead : [SELECT Id, Email FROM Lead WHERE Email IN : interactionsByEmail.keySet()]) {
                    leadsByEmail.put(lead.Email, lead);
            }   }
            if(interactionsByUTM.size() > 0) {
                // Builds campaignsByUTM to be able to search existing Campaigns based on UTM
                for(Campaign campaign : [SELECT Id, UTM__c FROM Campaign WHERE UTM__c IN : interactionsByUTM.keySet()]) {
                    campaignsByUTM.put(campaign.UTM__c, campaign);
            }   }
            for(Interaction__c interaction : interactions) {
                Campaign campaign    = campaignsByUTM.get(interaction.UTM__c);
                Lead lead            = leadsByEmail.get(interaction.Email__c);
                Location__c location = locationsByUPRN.get(interaction.UPRN__c);
                // Link the Interaction with the related Campaign based on the UTM
                if(campaign != null) {
                    interaction.Campaign__c = campaign.Id;
                }
                // Determines if there are existing Locations or will create a new ones
                if(location != null) {
                    interaction.Location__c = location.Id;
                    interaction.Account__c  = location.Account__c;
                }
                else {
                    location = InteractionHelper.createLocationFromInteraction(interaction);
                    // Determines if there are existing Leads or will create a new ones
                    if(lead != null) {
                        interaction.Lead__c = lead.Id;
                        location.Lead__c    = lead.Id;
                    }
                    else {
                        lead = InteractionHelper.createLeadFromInteraction(interaction);
                        // Link Lead with Campaign based on UTM
                        if(campaign != null) {
                            lead.Campaign__c = campaignsByUTM.get(interaction.UTM__c).Id;
                        }
                        newLeads.add(lead);
                    }
                    // Link Location with Market Area
                    if(String.isNotBlank(interaction.Market_Area__c)) {
                    	location.Parent_Location__c = LocationHelper.areasMap.get(interaction.Market_Area__c).Id;
                    }
                    newLocations.add(location);
            }   }
            // Checks if there are new Leads before insert
            if(newLeads.size() > 0) {
                insert newLeads;
                // After inserting new Leads links them with the Interactions
                for(Lead lead : newLeads) {
                    interactionsByEmail.get(lead.Email).Lead__c = lead.Id;
            }   } 
            // Checks if there are new Locations before insert
            if(newLocations.size() > 0) {
                // Link Locations with Leads
                for(Location__c location : newLocations) {
                    location.Lead__c = interactionsByUPRN.get(location.UPRN__c).Lead__c;
                }
                insert newLocations;
                // After inserting new Locations links them with the Interactions
                for(Location__c location : newLocations) {
                    interactionsByUPRN.get(location.UPRN__c).Location__c = location.Id;
}   }   }   */}   }