force-app/main/default/objects/Account_Development_Plan__c/Account_Development_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Development Plan</label>
    <nameField>
        <label>Account Development Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Development Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Development_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Development Plans</relationshipLabel>
    <relationshipName>Account_Development_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Development_Plan__c/fields/ADP_Review_Frequency__c.field-meta.xml
<CustomField>
    <fullName>ADP_Review_Frequency__c</fullName>
    <label>ADP Review Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Development_Plan__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Month</fullName>
            </value>
            <value>
                <fullName>3 Months</fullName>
            </value>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>12 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/ADPTriggerHandler.cls
public class ADPTriggerHandler {
    public static void createADPReviewTasks(Map<Id, Account_Development_Plan__c> newADPs, Map<Id, Account_Development_Plan__c> oldADPs) {
        Set<Id> accountIds = new Set<Id>();
        Set<Id> adpIds     = new Set<Id>();
        // Builds adpIds set to retrive existing ADP Review Tasks
        for(Account_Development_Plan__c adp : newADPs.values()) {
            // New ADPs
            if(oldADPs == null && String.isNotEmpty(adp.Period__c) && String.isNotEmpty(adp.ADP_Review_Frequency__c) && adp.From__c != null) {
                accountIds.add(adp.Account__c);
                adpIds.add(adp.Id);
            }
            // Changed ADPs
            else if(oldADPs != null) {
                Account_Development_Plan__c oldADP = oldADPs.get(adp.Id);
                // Determine if any of the relevant fields were changed
                if((adp.Period__c != oldADP.Period__c || adp.ADP_Review_Frequency__c != oldADP.ADP_Review_Frequency__c || adp.From__c != oldADP.From__c) && String.isNotEmpty(adp.Period__c) && adp.From__c != null) {
                    accountIds.add(adp.Account__c);
                    adpIds.add(adp.Id);
        }   }   }
        if(adpIds.size() > 0) {
            Map<Id, Account> adpAccounts = new Map<Id, Account> ([SELECT Id, OwnerId, Name FROM Account WHERE Id IN : accountIds]);
            List<Task> newADPReviewTasks = new List<Task>();
            List<Task> oldADPReviewTasks = new List<Task>();
            // Building ADP Review Tasks list that will be deleted
            for(Task adpTask : [SELECT Id FROM Task WHERE WhatId IN : adpIds AND Status =: Constants.TASK_STATUS_1]) {
                oldADPReviewTasks.add(adpTask);
            }
            // Checks if there are old ADP Review Tasks before delete
            if(oldADPReviewTasks.size() > 0) {
                delete oldADPReviewTasks;
            }
            // Building ADP Review Tasks list that will be inserted
            for(Id adpId : adpIds) {
                Account_Development_Plan__c adp = newADPs.get(adpId);
                // Creating ADP Review Tasks for each period based on start date and frequency
                if(adp != null) {
                    newADPReviewTasks.addAll(ADPHelper.createADPReviewTasks(adpAccounts.get(adp.Account__c), adp));
            }   }
            // Checks if there are new ADP Review Tasks before insert
            if(newADPReviewTasks.size() > 0) {
                insert newADPReviewTasks;
}   }   }   }