force-app/main/default/objects/Account_Development_Plan__c/Account_Development_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Development Plan</label>
    <nameField>
        <label>Account Development Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Development Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Development_Plan__c/fields/ADP_Review_Frequency__c.field-meta.xml
<CustomField>
    <fullName>ADP_Review_Frequency__c</fullName>
    <label>ADP Review Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Development_Plan__c/fields/Days_to_Complete_ADP_Review__c.field-meta.xml
<CustomField>
    <fullName>Days_to_Complete_ADP_Review__c</fullName>
    <label>Days to Complete ADP Review</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Development_Plan__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Month</fullName>
            </value>
            <value>
                <fullName>3 Months</fullName>
            </value>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>12 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/ADPTriggerTest.cls
@isTest
public class ADPTriggerTest {
    public static List<Task> adpReviewTasks;
    public static testMethod void createADPReviewTasksTest() {
        Account account                 = TestDataFactory.createAccount('Test Account', true);
        Account_Development_Plan__c adp = TestDataFactory.createADP(account.Id, false);
        // Test ADP Review Tasks automation when creating and updating Account Development Plan
        Test.startTest();
        // Test ADP Review Tasks creation when creating Account Development Plan
        adp.ADP_Review_Frequency__c = Constants.UTILITIES_DATE_FREQUENCY_1;
        adp.Period__c               = Constants.UTILITIES_DATE_PERIOD_1;
        insert adp;
        // Asserting the ADP Review Tasks were created
        adpReviewTasks = [SELECT Id FROM Task];
        System.assertEquals(adpReviewTasks.size(), 1);
        // Test ADP Review Tasks creation when updating Account Development Plan
        adp.ADP_Review_Frequency__c = Constants.UTILITIES_DATE_FREQUENCY_1;
        adp.Period__c               = Constants.UTILITIES_DATE_PERIOD_2;
        update adp;
        // Asserting the ADP Review Tasks were created
        adpReviewTasks = [SELECT Id FROM Task];
        System.assertEquals(adpReviewTasks.size(), 3);
        // Test ADP Review Tasks deletion when updating Account Development Plan
        adp.ADP_Review_Frequency__c = Constants.UTILITIES_DATE_FREQUENCY_2;
        adp.Period__c               = Constants.UTILITIES_DATE_PERIOD_2;
        update adp;
        // Asserting the ADP Review Tasks were created
        adpReviewTasks = [SELECT Id FROM Task];
        System.assertEquals(adpReviewTasks.size(), 1);
        // Test ADP Review Tasks creation when updating Account Development Plan
        adp.ADP_Review_Frequency__c = Constants.UTILITIES_DATE_FREQUENCY_2;
        adp.Period__c               = Constants.UTILITIES_DATE_PERIOD_3;
        update adp;
        // Asserting the ADP Review Tasks were created
        adpReviewTasks = [SELECT Id FROM Task];
        System.assertEquals(adpReviewTasks.size(), 2);
        // Test ADP Review Tasks creation when updating Account Development Plan
        adp.ADP_Review_Frequency__c = Constants.UTILITIES_DATE_FREQUENCY_1;
        adp.Period__c               = Constants.UTILITIES_DATE_PERIOD_4;
        update adp;
        // Asserting the ADP Review Tasks were created
        adpReviewTasks = [SELECT Id FROM Task];
        System.assertEquals(adpReviewTasks.size(), 12);
        Test.stopTest();
    }
    public static testMethod void createADPReviewTasksBulkTest() {
        List<Account_Development_Plan__c> adps = new List<Account_Development_Plan__c>();
        Account account                        = TestDataFactory.createAccount('Test Account', true);
        // Creating 200 Account Development Plan records
        for(Integer i = 0; i < 200; i++) {
            Account_Development_Plan__c adp    = TestDataFactory.createADP(account.Id, false);
            adp.ADP_Review_Frequency__c        = Constants.UTILITIES_DATE_FREQUENCY_3;
            adp.Days_to_Complete_ADP_Review__c = 1;
            adp.From__c                        = System.today();
            adp.Period__c                      = Constants.UTILITIES_DATE_PERIOD_4;
            // Building Account list to insert
            adps.add(adp);
        }
        // Test ADP Review Tasks creation when creating bulk Account Development Plans
        Test.startTest();
        insert adps;
        // Asserting the ADP Review Tasks were created
        adpReviewTasks = [SELECT Id FROM Task];
        System.assertEquals(adpReviewTasks.size(), 200);
        Test.stopTest();
}   }