force-app/main/default/objects/Account/fields/Channel_Forecast_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Channel_Forecast_Start_Date__c</fullName>
    <label>Channel Forecast Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ForecastPeriod__c.field-meta.xml
<CustomField>
    <fullName>ForecastPeriod__c</fullName>
    <label>Forecast Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 Months</fullName>
            </value>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>12 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Forecast__c/Channel_Forecast__c.object-meta.xml
<CustomObject>
    <label>Channel Forecast</label>
    <nameField>
        <displayFormat>C-F-{MM}{000}{YY}</displayFormat>
        <label>Channel Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountTriggerTest.cls
@isTest
public class AccountTriggerTest {
    public static List<Channel_Forecast__c> channelForecasts;
    public static testMethod void createChannelForecastsTest() {
        Account account = TestDataFactory.createAccount('Test Account', false);
        // Test Channel Forecasts automation when creating and updating Account
        Test.startTest();
        // Test Channel Forecasts creation when creating Account
        account.Channel_Forecast_Start_Date__c = System.today();
        account.ForecastPeriod__c              = Constants.UTILITIES_DATE_PERIOD_2;
        insert account;
        // Asserting the Channel Forecasts were created
        channelForecasts = [SELECT Id FROM Channel_Forecast__c];
        System.assertEquals(channelForecasts.size(), 3);
        // Test Channel Forecasts creation when updating Account
        account.Channel_Forecast_Start_Date__c = System.today();
        account.ForecastPeriod__c              = Constants.UTILITIES_DATE_PERIOD_4;
        update account;
        // Asserting the Channel Forecasts were created
        channelForecasts = [SELECT Id FROM Channel_Forecast__c];
        System.assertEquals(channelForecasts.size(), 12);
        // Test Channel Forecasts deletion when updating Account
        account.Channel_Forecast_Start_Date__c = System.today();
        account.ForecastPeriod__c              = Constants.UTILITIES_DATE_PERIOD_3;
        update account;
        // Asserting the Channel Forecasts were deleted
        channelForecasts = [SELECT Id FROM Channel_Forecast__c];
        System.assertEquals(channelForecasts.size(), 6);
        Test.stopTest();
    }
    public static testMethod void createChannelForecastsBulkTest() {
        List<Account> accounts = new List<Account>();
        // Creating 200 Account records
        for(Integer i = 0; i < 200; i++) {
            Account account                        = TestDataFactory.createAccount('Test Account ' + String.valueOf(i), false);
            account.Channel_Forecast_Start_Date__c = System.today();
            account.ForecastPeriod__c              = Constants.UTILITIES_DATE_PERIOD_2;
            // Building Account list to insert
            accounts.add(account);
        }
        // Test Channel Forecasts creation when creating bulk Accounts
        Test.startTest();
        insert accounts;
        // Asserting the Channel Forecasts were created
        channelForecasts = [SELECT Id FROM Channel_Forecast__c];
        System.assertEquals(channelForecasts.size(), 600);
        Test.stopTest();
}   }