force-app/main/default/objects/Giganet_Product__c/Giganet_Product__c.object-meta.xml
<CustomObject>
    <label>Giganet Product</label>
    <nameField>
        <label>Giganet Product  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Giganet Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Giganet_Product__c/fields/Install_Amount__c.field-meta.xml
<CustomField>
    <fullName>Install_Amount__c</fullName>
    <label>Install Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Giganet_Product__c/fields/Install_Gross_Profit__c.field-meta.xml
<CustomField>
    <fullName>Install_Gross_Profit__c</fullName>
    <label>Install Gross Profit</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Giganet_Product__c/fields/Monthly_Contract_GP__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Contract_GP__c</fullName>
    <label>Monthly Contract GP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Giganet_Product__c/fields/Monthly_Contract_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Contract_Revenue__c</fullName>
    <label>Monthly Contract Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Giganet_Product__c/fields/Number_of_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Users__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Giganet_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Giganet Products</relationshipLabel>
    <relationshipName>Giganet_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Giganet_Product__c/fields/Router__c.field-meta.xml
<CustomField>
    <fullName>Router__c</fullName>
    <label>Router</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Juniper SRX300</fullName>
            </value>
            <value>
                <fullName>Juniper EX2300-C-12T</fullName>
            </value>
            <value>
                <fullName>Juniper SRX340</fullName>
            </value>
            <value>
                <fullName>Juniper EX4300-24T 10GE</fullName>
            </value>
            <value>
                <fullName>UltraHub 1</fullName>
            </value>
            <value>
                <fullName>UltraHub 2</fullName>
            </value>
            <value>
                <fullName>UltraHub 3</fullName>
            </value>
            <value>
                <fullName>SuperHub 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Giganet_Product__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BT Wholesale</fullName>
            </value>
            <value>
                <fullName>CityFibre</fullName>
            </value>
            <value>
                <fullName>Colt</fullName>
            </value>
            <value>
                <fullName>Giganet Local</fullName>
            </value>
            <value>
                <fullName>Glide</fullName>
            </value>
            <value>
                <fullName>Openreach</fullName>
            </value>
            <value>
                <fullName>SSE</fullName>
                <label>Neos</label>
            </value>
            <value>
                <fullName>TTB</fullName>
            </value>
            <value>
                <fullName>Virgin Media</fullName>
            </value>
            <value>
                <fullName>Virtual 1</fullName>
            </value>
            <value>
                <fullName>Zen</fullName>
            </value>
            <value>
                <fullName>Telcoswitch</fullName>
            </value>
            <value>
                <fullName>Ubiquiti</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Monthly_Contract_GP__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Contract_GP__c</fullName>
    <description>Enter the monthly GP for the service</description>
    <label>Monthly Contract GP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Monthly_Contract_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Contract_Revenue__c</fullName>
    <description>Enter the monthly revenue for the service</description>
    <label>Monthly Contract Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <description>Enter the supplier of the circuit.</description>
    <label>Supplier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BT Wholesale</fullName>
            </value>
            <value>
                <fullName>CityFibre</fullName>
            </value>
            <value>
                <fullName>Colt</fullName>
            </value>
            <value>
                <fullName>Giganet Local</fullName>
            </value>
            <value>
                <fullName>Glide</fullName>
            </value>
            <value>
                <fullName>Openreach</fullName>
            </value>
            <value>
                <fullName>SSE</fullName>
                <label>Neos</label>
            </value>
            <value>
                <fullName>TTB</fullName>
            </value>
            <value>
                <fullName>Virgin Media</fullName>
            </value>
            <value>
                <fullName>Virtual 1</fullName>
            </value>
            <value>
                <fullName>Zen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>[Delete] Supplier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Colt</fullName>
            </value>
            <value>
                <fullName>CityFibre</fullName>
            </value>
            <value>
                <fullName>Entanet</fullName>
            </value>
            <value>
                <fullName>Glide</fullName>
            </value>
            <value>
                <fullName>Openreach</fullName>
            </value>
            <value>
                <fullName>SSE</fullName>
            </value>
            <value>
                <fullName>TalkTalk Business</fullName>
            </value>
            <value>
                <fullName>Virtual1</fullName>
            </value>
            <value>
                <fullName>Zen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GiganetProductTriggerHandler.cls
public with sharing class GiganetProductTriggerHandler {
    public static void createOpportunityProducts(Map<Id, Giganet_Product__c> newMap) {
        Map<String, Product2> productsByName     = new Map<String, Product2>();
        Map<String, Account> suppliersByName     = new Map<String, Account>();
        List<Product__c> newOpportunityProducts1 = new List<Product__c>();
        List<Product__c> newOpportunityProducts2 = new List<Product__c>();
        Set<String> productNames                 = new Set<String>();
        Set<String> supplierNames                = new Set<String>();
        // Builds productNames and supplierNames sets to retrive existing records by Name
        for(Giganet_Product__c newRecord : newMap.values()) {
            productNames.add(newRecord.Name);
            productNames.add(newRecord.Router__c);
            supplierNames.add(newRecord.Supplier__c);
        }
        productsByName  = ProductHelper.getProductsByName(productNames);
        suppliersByName = AccountHelper.getSuppliersByName(supplierNames);
        // 
        for(Giganet_Product__c newRecord : newMap.values()) {
            Product2 product = productsByName.get(newRecord.Name);
            Account supplier = suppliersByName.get(newRecord.Supplier__c);
            //
            Product__c opportunityProduct1         = new Product__c();
            opportunityProduct1.Name               = newRecord.Name;
            opportunityProduct1.Opportunity__c     = newRecord.Opportunity__c;
            opportunityProduct1.Giganet_Product__c = newRecord.Id;
            opportunityProduct1.Product__c         = product  != null ? product.Id  : null;
            opportunityProduct1.Supplier__c        = supplier != null ? supplier.Id : null;
            opportunityProduct1.Install_Amount__c  = newRecord.Install_Amount__c;
            opportunityProduct1.Install_GP__c      = newRecord.Install_Gross_Profit__c;
            opportunityProduct1.Monthly_GP__c      = newRecord.Monthly_Contract_GP__c;
            opportunityProduct1.Monthly_Revenue__c = newRecord.Monthly_Contract_Revenue__c;
            opportunityProduct1.Quantity__c        = newRecord.Number_of_Users__c;
            opportunityProduct1.Term__c            = newRecord.Term__c;
            //
            newOpportunityProducts1.add(opportunityProduct1);
        }
        insert newOpportunityProducts1;
        
        newOpportunityProducts1 = [SELECT Id, Name, Opportunity__c , Giganet_Product__c FROM Product__c WHERE Giganet_Product__c IN : newMap.keySet()];
        
        for(Product__c opportunityProduct : newOpportunityProducts1) {
            Product2 product = productsByName.get(newMap.get(opportunityProduct.Giganet_Product__c).Router__c);
            //
            if(product != null) {
                Product__c opportunityProduct2         = new Product__c();
                opportunityProduct2.Name               = product.Name;
                opportunityProduct2.Parent__c          = opportunityProduct.Id;
                opportunityProduct2.Opportunity__c     = opportunityProduct.Opportunity__c;
                opportunityProduct2.Giganet_Product__c = opportunityProduct.Giganet_Product__c;
                opportunityProduct2.Product__c         = product.Id;
                opportunityProduct2.Quantity__c        = 1;
                //
                newOpportunityProducts2.add(opportunityProduct2);
        }    }
        if(newOpportunityProducts2.size() > 0) {
            insert newOpportunityProducts2;
    }   }
    public static void deleteOpportunityProducts(Map<Id, Giganet_Product__c> oldMap) {
        Boolean functionSwitch = Utilities.functionSwitch.get('GiganetProductTriggerHandler.deleteOpportunityProducts');
        // Determining if function should run or not
        if(functionSwitch == null || functionSwitch) {
            List<Product__c> opportunityProducts = [SELECT Id FROM Product__c WHERE Giganet_Product__c IN : oldMap.keySet()];
            // Deleting all related Opportunity Products
            if(opportunityProducts.size() > 0) {
                Utilities.functionSwitch.put('ProductTriggerHandler.deleteGiganetProducts', false);
                delete opportunityProducts;
}   }   }   }