force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <label>Interaction</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Property</value>
        </filterItems>
        <infoMessage>Only locations of type property are allowed.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Registered_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interaction__c/fields/UPRN__c.field-meta.xml
<CustomField>
    <fullName>UPRN__c</fullName>
    <label>UPRN</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Distinguishes between area / region and residential / commercial property.</description>
    <inlineHelpText>Distinguishes between area / region and residential / commercial property.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Region</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Market Area</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/fields/UPRN__c.field-meta.xml
<CustomField>
    <fullName>UPRN__c</fullName>
    <label>UPRN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InteractionHelper.cls
public class InteractionHelper {
    public static Account createAccountFromInteraction(Interaction__c interaction) {
        Account account = new Account();
        
        return account;
    }
    public static Lead createLeadFromInteraction(Interaction__c interaction) {
        Lead lead       = new Lead();/* Test commit
        lead.Company    = interaction.Company__c;
        lead.Email      = interaction.Email__c;
        lead.FirstName  = interaction.First_Name__c;
        lead.LastName   = interaction.Last_Name__c;
        lead.Street     = interaction.Street__c;
        lead.Postalcode = interaction.Postcode__c;
        lead.City       = interaction.City__c;
        if(interaction.Location_Type__c == Constants.INTERACTION_LOCATION_TYPE_1) {
            lead.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get(Constants.LEAD_RECORD_TYPE_1).getRecordTypeId();
        }
        else {
            lead.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get(Constants.LEAD_RECORD_TYPE_3).getRecordTypeId();
        }*/
        return lead;
    }
    public static Location__c createLocationFromInteraction(Interaction__c interaction) {
        Location__c location  = new Location__c();/*
        location.Name         = interaction.UPRN__c;
        location.UPRN__c      = interaction.UPRN__c;
        location.Type__c      = interaction.Location_Type__c;
        location.Street__c    = interaction.Street__c;
        location.Postcode__c  = interaction.Postcode__c;
        location.City__c      = interaction.City__c;
        location.RecordTypeId = Schema.SObjectType.Location__c.getRecordTypeInfosByName().get(Constants.LOCATION_RECORD_TYPE_2).getRecordTypeId();
        */
        return location;
}   }